language: java

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_446ef87682bf_key -iv $encrypted_446ef87682bf_iv -in private-key.gpg.enc -out private-key.gpg -d

install:
  - ./gradlew -v

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew dokka publish
  on:
    tags: true

env:
  global:
    - secure: rNIoF+TxuqlzZpuu5sWsEviLVDv9G4Hh+zf7eiEv9ikZ1IWsTjghfmEssvJr2t8UcV4L3Ff6tSgwlXbxI7sqZLRRAlivoDbtkvg6tlm2srYf/Hqaf/vNywQULZ4UfVRmoNKJ6MToA9Beisr+lYrSW7Sh8Qvn5eEUEynEtAZPwfP9/ILr5SXFqJ16QU8d1+ECed6zNvt7J+ddWlXuMiAA0pdkIUzTkeIPU1b4phOA1lA6SXWhXsUciYaMj2u5dyddP1K+gvDaqXbZl0eaOsvXMCNif321EI41RS+fGcouN4V3p0z8s/6LBhSbOYrkgKorTl9OAg4YX7utNM0ipldnz/+VjCxcXs2j/AbaLlSvdeKgCSn/1O4NYA9ZZ9mBt14wWTIHSFbdIv7DYOz7HEJFHJ9PyAyIs2INkvaTgye4I0Ogu+piLxszkztKSp/j/hsuxqRaFD1Xd6LDDyJGOsgZT19EvJfuGplkwDaA02ysnwoJ+4MJbC4/sxiJwtRr8FUd0Lp+QrLcsRn6gy73Qbg5u6nfa5NPAWCe7vvUj/5avOnUFhZZslPic0UcTLGGEroiKsW92pqNCg8+EMzVnTTUIpU4r4plUrJ2G1nO0WAXbcJwKhKGrpy99N2sJ8j+pSbUuwNUHSRrzRzajMi6pm1PHzzFNy2mpf8smHON/GGbK+o=