language: java

jdk:
  - oraclejdk8

before_install:
  - openssl aes-256-cbc -K $encrypted_446ef87682bf_key -iv $encrypted_446ef87682bf_iv -in private-key.gpg.enc -out private-key.gpg -d

install:
  - ./gradlew -v

script:
  - ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew dokka publish
  on:
    tags: true

env:
  global:
    - secure: d4dtF6bMJxSwuibeXWsw/AsoNFLuoTGE/7m++JCplb4iedpscp2CKeOtuwl2dRSYV2ecGL7ZPmxhHu6DypVYq7MCItHj7yIXb+exaBH46pkfPbV4hMVedK9TkelU9W4TuvtC1KcgEsSjSYKxrpAR1U7DI2Ohz2jzpVZEG1RRKOAJc+NRCLlvmZrmFxnY99Uc8qCwfGpW+f8/QuHpTtfmQ+j851w1sthwyZXVs/DHS1o3ol55G8L2MQhWc2/EKv62q4ySNlaXIN2bNyB+9W8By4QUUgkwDoJftV1DwoqCcLFlMn+ZYEZ00gedDu6aqbHgPSaerd/BTKAgkzqmlvx/3nYus9Du68QTousEWNISW03sBQX4Px9NLPn9x6kKMqLhO6y3PwibEvcMZOud2J058L3Tmkrq6uOIzkkoLV5kn9fFIsjSoPmjxgvSrknT//MF6IhNS6qw0+rlPnOaWrI0L2if6yaT2pnLyk3anv4l3n+p+uif5mntB+Z1wV22SF05zg086UUcdyPo3c1uxCBkZRg+lW1RvUWFKPkYgCt2O1blAHY4JCSPoeJ3+ean0yMSYU71E7DW+1XZ79H6nYxR5gOHzxrWY10p3pmij4L9WEXef3QYwk1iK133FpWJfh1akWhr9nkra+2ELK1yG4elX1ZDet29OiKll0Gc6aO3IIM=